---
- name: install httpd
  yum: name=httpd state=installed

- name: index file copy
  template: src=index.html.j2 dest=/var/www/html/index.html owner=root  group=root  mode=0644
  notify:
   - Restart httpd
   - Reload httpd
